# Generated by Django 5.2.1 on 2025-05-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(null=True, upload_to='pokemon_images'),
        ),
    ]
